name: vishnu_training_and_placements
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pie_chart: ^5.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: Alata
      fonts:
        - asset: fonts/Alata-Regular.ttf