name: vishnu_training_and_placements
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pie_chart: ^5.3.2
  file_picker: ^5.3.1
  excel: ^2.1.0
  intl: ^0.18.1
  fl_chart: ^0.63.0
  table_calendar: ^3.0.9

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Alata
      fonts:
        - asset: fonts/Alata-Regular.ttf