name: vishnu_training_and_placements
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  pie_chart: ^5.4.0
  flutter_lints: ^5.0.0
  http: ^1.3.0
  file_picker: ^10.0.0
  excel: ^4.0.6
  intl: ^0.20.2
  fl_chart: ^0.70.2
  table_calendar: ^3.0.0
  lottie: ^3.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Alata
      fonts:
        - asset: fonts/Alata-Regular.ttf